debug_log = false

[simulation]
enable = true
duration = 150
resolution = 0.1
test_mode_en = false
test_duration = 3
test_resolution = 1
iterations = 1
tuning = false
input_type="ref" # ref, ref_square, torque, sine, square
verbose = false

[controller]
enable = true
c = [ 1, 1, 1,]
k = 2
kj = 2
kd = 4
ki = 50
T_max = 1000
T_min = 0
filter_coef = 0
t_sample = 0.1
type = "backstepping" # pid, backstepping, adaptive
sub_type = "Zarourati" # Nadafi_FNDO, Nadafi_MFNDO, Shen, Kararouti
adaptive_gain = 0.1
detection_en = true

[backstepping]
alpha = 1 # makes peaks and troughs more pointy
beta = 1.8 # similar to kd
k = 100 # similar to kp
eta_1 = 0.1
upsilon = 0.01
c_1 = 0.01
c_2 = 0.1

[observer]
enable = true
feedback_en = true
t_sample = 0.01
gain = [ 3.00, 0.005, 0.000 ]

[wheels]
config = "ortho" # tetra, ortho, pyramid, custom
mass = 0.31
radius = 0.066
height = 0.025
max_speed_rpm = 10000
max_torque = 0.5
num_wheels = 3
D = [ [ -1, -1, 1, 1,], [ 1, -1, -1, 1,], [ 1, 1, 1, 1,],]
friction_coef = 0.0000
saturation_enable = false
M_inertia = 0.05
use_inertia = false

[magt]
mag_moment_max = 50 # Am2
t_sample = 1
enable = false

[faults]
master_enable = true

[fault.0]
# mul_fault = [ 1.0, 1.0, 1.0, 0.0,]
# add_fault = [ 0.0, 0.0, 0.0, 0.0,]
mul_fault = [ 1.0, 0.0, 1.0,]
add_fault = [ 0, 0, 0,]
time = 0
master_enable = true

[fault.1]
# mul_fault = [ 1.0, 1.0, 1.0, 1.0,]
# add_fault = [ 0.0, -0.03, -0.04, 0.0,]
# add_fault = [ 0.0, 0.0, 0.0, 0.0,]
mul_fault = [ 1.0, 1.0, 1.0,]
add_fault = [ 0, 0, 0,]
time = 100
master_enable = false

[satellite]
mode="ref_pointing"
euler_init_en = true
euler_init = [ 0, 2, 0,]
# euler_init = [ 0, 0, 0,]
# q_init = [ -0.5, 0.3, 0.4, 0.7071,]
q_init = [ 0, 0, 0, 1,]
use_ref_euler = true
ref_euler = [ 0, 0, 0,]
use_ref_q = false
# ref_q = [ 0, 0, 0, 1,]
ref_q = [ 0.12707253, -0.17409001,  0.12707253,  0.96819307]
# ref_q = [ -0.9880316, 0.0, 0.0, 0.1542514 ]
use_ref_series = false
# ref_q_series = [[ 0.4871745, 0.0, 0.0, 0.8733046,], [ 0.0, 0.0, 0.0, 1.0 ]]
ref_q_series = [[ 0.12707253, -0.17409001,  0.12707253,  0.96819307], [ 0.0, 0.0, 0.0, 1.0 ]]
ref_t_series=[ 0, 30,]
w_init_dps = [ 0, 0, 0,]
wheels_control_enable = true
mass = 12
M_Inertia = [ [ 0.919, -0.023, -0.020], [ -0.023, 0.916, 0.009], [ -0.020, 0.009, 0.444] ]
# M_Inertia = [ [ 10.0, 1.2, 0.5,], [ 1.2, 19.0, 1.5,], [ 0.5, 1.5, 25.0,],]
# M_Inertia = [ [ 50.0, 1.2, 0.5,], [ 1.2, 50.0, 1.5,], [ 0.5, 1.5, 50.0,],]
# M_Inertia = [ [ 2.5, 0.0, 0.0,], [ 0.0, 3.5, 0.0,], [ 0.0, 0.0, 4.5,], ]
inertia_override = true

[orbit]
altitude_km = 500 # km

[disturbances]
enable = false
model = "Nadafi"

[output]
accuracy_enable = true
energy_enable = true
log_enable = true
append_date = false
pdf_output_enable = true
log_file_name_overide = "None"
separate_plots_display = false
show_plots = false

[satellite.dimensions]
x = 0.3
y = 0.3
z = 0.3
model = 'box'

[FDIR]
enable = false

[FDIR.wheels]
enable = false
inst_time_threshold = 10
inst_count_threshold = 5

[FDIR.satellite]
enable = false
w_max_dps = 10

[output.visualizer]
enable = false
file_path = "/opt/satellite-visualizer/dist/telemetry.json"
t_sample = 1.0